# Generated by Django 3.0.4 on 2020-03-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0013_auto_20200306_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Εταιρεία', models.CharField(max_length=100)),
                ('Serial', models.CharField(max_length=30)),
                ('Εναρξη', models.DateTimeField()),
                ('Μετρητής_έναρξης', models.PositiveIntegerField(blank=True, null=True)),
                ('Σημειώσεις', models.CharField(blank=True, max_length=500, null=True)),
                ('Κατάσταση', models.BooleanField(default=True)),
                ('Πελάτη_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer')),
            ],
        ),
    ]
