# Generated by Django 3.0.4 on 2020-03-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='Πελάτη_ID',
            new_name='Πελάτης',
        ),
    ]
