# Generated by Django 3.0.4 on 2020-03-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20200307_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='Κατάσταση',
            new_name='Ενεργό',
        ),
    ]
