# Generated by Django 3.0.4 on 2020-03-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_auto_20200310_1106'),
        ('machines', '0005_auto_20200311_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Πελάτης',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer'),
        ),
    ]
