# Generated by Django 3.0.4 on 2020-03-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20200311_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'verbose_name_plural': 'machines'},
        ),
    ]
