# Generated by Django 3.0.4 on 2020-03-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20200315_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'ordering': ['Πελάτης']},
        ),
    ]
