# Generated by Django 3.0.4 on 2020-03-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0014_auto_20200316_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='Ενεργό',
            new_name='Κατάσταση',
        ),
    ]
