# Generated by Django 3.0.4 on 2020-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_auto_20200316_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Εναρξη',
            field=models.DateField(blank=True, null=True),
        ),
    ]
