# Generated by Django 3.0.4 on 2020-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0019_auto_20200319_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Εναρξη',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία έναρξης'),
        ),
    ]
