# Generated by Django 3.0.4 on 2020-03-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0021_auto_20200319_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Εναρξη',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
