# Generated by Django 3.0.4 on 2020-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0022_auto_20200319_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Εναρξη',
            field=models.DateField(blank=True, null=True),
        ),
    ]
