# Generated by Django 3.0.4 on 2020-03-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0025_auto_20200321_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='Πελάτης',
            new_name='Πελάτη_ID',
        ),
    ]
