# Generated by Django 3.0.4 on 2020-03-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0027_auto_20200321_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Μοντέλο',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
