# Generated by Django 3.0.4 on 2020-03-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0030_auto_20200321_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Μετρητής_έναρξης',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
