# Generated by Django 3.0.4 on 2020-03-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0031_auto_20200321_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'ordering': ['Πελάτης']},
        ),
    ]
