# Generated by Django 3.0.4 on 2020-03-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_auto_20200322_0111'),
        ('machines', '0032_auto_20200322_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Πελάτης',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customers.Customer'),
            preserve_default=False,
        ),
    ]
