# Generated by Django 3.0.4 on 2020-03-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0033_auto_20200325_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'ordering': ['Πελάτης'], 'verbose_name_plural': 'Φωτοτυπικά'},
        ),
    ]
