# Generated by Django 3.0.4 on 2020-03-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0034_auto_20200328_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'ordering': ['Πελάτης'], 'verbose_name': 'Μηχανήματα', 'verbose_name_plural': 'Φωτοτυπικά'},
        ),
    ]
