# Generated by Django 3.0.4 on 2020-03-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0035_auto_20200330_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='Μοντέλο',
        ),
    ]
