# Generated by Django 3.0.4 on 2020-04-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_remove_machines_μοντέλο'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'ordering': ['Εταιρεία'], 'verbose_name': 'Μηχανήματα', 'verbose_name_plural': 'Φωτοτυπικά'},
        ),
    ]
