# Generated by Django 3.0.4 on 2020-04-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_auto_20200403_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Κατάσταση',
            field=models.BooleanField(default=True, help_text='<font color="red"><b>Ενεργό αν δεν έχει αποσυρθεί το μηχάνημα</b></font>'),
        ),
    ]
