# Generated by Django 3.0.4 on 2020-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_data', '0002_auto_20200403_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedata',
            name='Ενέργειες',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedata',
            name='Σκοπός',
            field=models.CharField(blank=True, help_text='Περιγραφή προβλήματος', max_length=100, null=True),
        ),
    ]
