# Generated by Django 3.0.4 on 2020-03-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0020_auto_20200319_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ημερομηνία', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία')),
                ('Σκοπός_Επίσκεψης', models.CharField(max_length=300, unique=True)),
                ('Ενέργειες', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Τεχνικός', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Σημειώσεις', models.TextField(blank=True, max_length=500, null=True)),
                ('Μετρητής', models.PositiveIntegerField(blank=True, null=True)),
                ('Επ_Service', models.PositiveIntegerField(blank=True, null=True)),
                ('ΔΤΕ', models.PositiveIntegerField(blank=True, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('Copier_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Machines')),
            ],
            options={
                'db_table': 'Service',
                'ordering': ['Ημερομηνία'],
            },
        ),
    ]
