# Generated by Django 3.0.4 on 2020-03-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200319_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Σκοπός_Επίσκεψης',
            field=models.CharField(max_length=300),
        ),
    ]
