# Generated by Django 3.0.4 on 2020-03-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200321_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Ημερομηνία',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
