# Generated by Django 3.0.4 on 2020-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20200321_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Ημερομηνία',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
