# Generated by Django 3.0.4 on 2020-03-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200321_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.RemoveField(
            model_name='services',
            name='Ημερομηνία',
        ),
    ]
