# Generated by Django 3.0.4 on 2020-03-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20200321_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['Ημερομηνία']},
        ),
        migrations.AddField(
            model_name='services',
            name='Ημερομηνία',
            field=models.DateField(blank=True, null=True),
        ),
    ]
