# Generated by Django 3.0.4 on 2020-03-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20200321_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Ημερομηνία',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
