# Generated by Django 3.0.4 on 2020-03-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20200322_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['Τεχνικός']},
        ),
    ]
