# Generated by Django 3.0.4 on 2020-03-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20200322_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Ημερομηνία',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
