# Generated by Django 3.0.4 on 2020-03-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20200322_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Ημερομηνία',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
