# Generated by Django 3.0.4 on 2020-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20200322_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Ημερομηνία',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
