# Generated by Django 3.0.4 on 2020-03-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_auto_20200322_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
    ]
