# Generated by Django 3.0.4 on 2020-03-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20200322_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-ΔΤΕ']},
        ),
    ]
