# Generated by Django 3.0.4 on 2020-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20200325_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('Ημερομηνία',), 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='services',
            name='Price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='ΔΤΕ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
