# Generated by Django 3.0.4 on 2020-03-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20200328_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['Ημερομηνία'], 'verbose_name_plural': 'Συντήρηση'},
        ),
    ]
