# Generated by Django 3.0.4 on 2020-03-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_auto_20200328_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['Ημερομηνία'], 'verbose_name': 'Συντήρηση', 'verbose_name_plural': 'Συντήρηση'},
        ),
    ]
