# Generated by Django 3.0.4 on 2020-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20200330_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Επ_Service',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Μετρητής',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
