# Generated by Django 3.0.4 on 2020-04-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_auto_20200403_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-ΔΤΕ'], 'verbose_name': 'Συντήρηση', 'verbose_name_plural': 'Συντήρηση'},
        ),
    ]
