# Generated by Django 3.0.4 on 2020-04-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_auto_20200403_2157'),
        ('services', '0044_auto_20200403_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Copier_ID',
            field=models.ForeignKey(db_column='Copier_ID', on_delete=django.db.models.deletion.PROTECT, to='machines.Machines'),
        ),
    ]
