# Generated by Django 3.0.4 on 2020-03-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0041_auto_20200330_0820'),
        ('customers', '0043_auto_20200330_0820'),
        ('machines', '0035_auto_20200330_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ημερομηνία', models.DateField(help_text='Ημερομηνία')),
                ('Πελάτης', models.CharField(max_length=100)),
                ('Μηχάνημα', models.CharField(max_length=100)),
                ('Σκοπός', models.CharField(max_length=100)),
                ('Ενέργειες', models.CharField(max_length=100)),
                ('Τεχνικός', models.CharField(max_length=100)),
                ('Ημ_Ολοκλ', models.DateField(help_text='Ημερομηνία ολοκλήρωσης')),
                ('Επείγων', models.CharField(max_length=100)),
                ('Τηλέφωνο', models.CharField(max_length=100)),
                ('Σημειώσεις', models.CharField(max_length=100)),
                ('ΔΤΕ', models.CharField(max_length=100)),
                ('Μετρητής', models.CharField(max_length=100)),
                ('Επ_Service', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Κατάσταση', models.BooleanField(default=True)),
                ('Copier_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Machines')),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer')),
                ('Service_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Services')),
            ],
            options={
                'verbose_name': 'Εργασίες',
                'verbose_name_plural': 'Ημερολόγιο',
                'db_table': 'Calendar',
                'ordering': ['Ημερομηνία'],
            },
        ),
    ]
