# Generated by Django 3.0.4 on 2020-03-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='Service_ID',
        ),
    ]
