# Generated by Django 3.0.4 on 2020-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_remove_calendar_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='Service_ID',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
