# Generated by Django 3.0.4 on 2020-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_calendar_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='ΔΤΕ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Επ_Service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Επείγων',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Ημ_Ολοκλ',
            field=models.DateField(blank=True, help_text='Ημερομηνία ολοκλήρωσης', null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Μετρητής',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Σημειώσεις',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Τηλέφωνο',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
