# Generated by Django 3.0.4 on 2020-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_auto_20200330_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Ενέργειες',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Τεχνικός',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
