# Generated by Django 3.0.4 on 2020-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_auto_20200330_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Ημ_Ολοκλ',
            field=models.CharField(blank=True, help_text='Ημερομηνία ολοκλήρωσης', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Ημερομηνία',
            field=models.CharField(help_text='Ημερομηνία', max_length=10),
        ),
    ]
