# Generated by Django 3.0.4 on 2020-04-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_auto_20200330_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Σημειώσεις',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
