# Generated by Django 3.0.4 on 2020-04-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_remove_machines_μοντέλο'),
        ('Calendar', '0008_auto_20200402_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Copier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Machines'),
        ),
    ]
