# Generated by Django 3.0.4 on 2020-04-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0014_auto_20200403_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Service_ID',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
