# Generated by Django 3.0.4 on 2020-04-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0015_auto_20200403_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Επ_Service',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Μετρητής',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
