# Generated by Django 3.0.4 on 2020-04-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_remove_machines_μοντέλο'),
        ('Calendar', '0016_auto_20200403_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Copier_ID',
            field=models.ForeignKey(db_column='Copier_ID', on_delete=django.db.models.deletion.PROTECT, to='machines.Machines'),
        ),
    ]
