# Generated by Django 3.0.4 on 2020-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0017_auto_20200403_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Σκοπός',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
