# Generated by Django 3.0.4 on 2020-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0021_auto_20200405_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Σημειώσεις',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
