# Generated by Django 3.0.4 on 2020-04-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_auto_20200403_2206'),
        ('Calendar', '0024_auto_20200411_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Service_ID',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Services'),
        ),
    ]
