# Generated by Django 3.0.4 on 2020-04-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0026_auto_20200411_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Service_ID',
            field=models.SmallIntegerField(blank=True, help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', null=True),
        ),
    ]
