# Generated by Django 3.0.4 on 2020-04-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0027_auto_20200411_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Ημ_Ολοκλ',
            field=models.DateField(blank=True, help_text='Ημερομηνία ολοκλήρωσης', max_length=10, null=True),
        ),
    ]
