# Generated by Django 3.0.4 on 2020-04-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0028_auto_20200415_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Ημ_Ολοκλ',
            field=models.CharField(blank=True, help_text='Ημερομηνία ολοκλήρωσης', max_length=10, null=True),
        ),
    ]
