# Generated by Django 3.0.4 on 2020-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0029_auto_20200415_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Price',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Service_ID',
            field=models.SmallIntegerField(blank=True, default='', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='ΔΤΕ',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Ενέργειες',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Επ_Service',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Επείγων',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Ημ_Ολοκλ',
            field=models.CharField(blank=True, default='', help_text='Ημερομηνία ολοκλήρωσης', max_length=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Μετρητής',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Σημειώσεις',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Σκοπός',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Τεχνικός',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Τηλέφωνο',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
