# Generated by Django 3.0.4 on 2020-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenderEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.SmallIntegerField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Email Αποστολέα',
                'verbose_name_plural': 'Αποστολής Emails',
                'db_table': 'Sender_emails',
            },
        ),
    ]
