# Generated by Django 3.0.4 on 2020-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderemails',
            name='port',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
