# Generated by Django 3.0.4 on 2020-04-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Copiers_Log', '0004_auto_20200416_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copierslog',
            old_name='Ημερωμηνία',
            new_name='Ημερομηνία',
        ),
    ]
