# Generated by Django 3.0.4 on 2020-04-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0049_auto_20200403_1822'),
        ('services', '0044_auto_20200403_1835'),
        ('Calendar', '0020_auto_20200403_2054'),
        ('machines', '0037_auto_20200403_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARTS_NR', models.CharField(blank=True, max_length=100, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.CharField(blank=True, max_length=100, null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, max_length=100, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, max_length=100, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.CharField(blank=True, max_length=100, null=True)),
                ('Calendar_ID', models.ForeignKey(db_column='Calendar_ID', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', on_delete=django.db.models.deletion.PROTECT, to='Calendar.Calendar')),
                ('Customer_ID', models.ForeignKey(db_column='Customer_ID', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', on_delete=django.db.models.deletion.PROTECT, to='customers.Customer')),
                ('Service_ID', models.ForeignKey(db_column='Service_ID', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', on_delete=django.db.models.deletion.PROTECT, to='services.Services')),
                ('ΜΗΧΑΝΗΜΑ', models.ForeignKey(db_column='ΜΗΧΑΝΗΜΑ', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', on_delete=django.db.models.deletion.PROTECT, to='machines.Machines')),
            ],
            options={
                'verbose_name': 'Ανταλλακτικό',
                'verbose_name_plural': 'Ανταλλακτικά',
                'db_table': 'Ανταλλακτικά',
            },
        ),
    ]
