# Generated by Django 3.0.4 on 2020-04-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0003_auto_20200403_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='Calendar_ID',
            field=models.SmallIntegerField(blank=True, db_column='Calendar_ID', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='Service_ID',
            field=models.SmallIntegerField(blank=True, db_column='Service_ID', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', null=True),
        ),
    ]
