# Generated by Django 3.0.4 on 2020-04-03 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_auto_20200403_2157'),
        ('spareparts', '0004_auto_20200403_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='ΜΗΧΑΝΗΜΑ',
            field=models.ForeignKey(blank=True, db_column='ΜΗΧΑΝΗΜΑ', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.Machines'),
        ),
    ]
