# Generated by Django 3.0.4 on 2020-04-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0007_auto_20200403_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='ΜΗΧΑΝΗΜΑ',
            field=models.CharField(default='', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', max_length=100),
        ),
    ]
