# Generated by Django 3.0.4 on 2020-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0013_auto_20200404_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='ΜΗΧΑΝΗΜΑ',
            field=models.CharField(default='', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', max_length=200),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='ΠΑΡΑΤΗΡΗΣΗΣ',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='ΠΕΡΙΓΡΑΦΗ',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
