# Generated by Django 3.0.4 on 2020-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0015_auto_20200407_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='Calendar_ID',
            field=models.CharField(blank=True, db_column='Calendar_ID', help_text='<font color="red"><b>Δεν το αλλάζουμε</b></font>', max_length=10, null=True),
        ),
    ]
