# Generated by Django 3.0.4 on 2020-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0016_auto_20200407_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='ΠΑΡΑΤΗΡΗΣΗΣ',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
