# Generated by Django 3.0.4 on 2020-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Νame', models.CharField(default='Ονομα', max_length=200)),
                ('Phone', models.CharField(default='Τηλέφωνο', max_length=100)),
                ('Επωνυμία_Επιχείρησης', models.CharField(max_length=200)),
                ('Ονοματεπώνυμο', models.CharField(max_length=200)),
                ('Διεύθυνση', models.CharField(max_length=200)),
                ('Πόλη', models.CharField(max_length=100)),
                ('Ταχ_Κώδικας', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Περιοχή', models.CharField(max_length=200)),
                ('Τηλέφωνο', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Κινητό', models.CharField(max_length=200)),
                ('Φαξ', models.CharField(max_length=200)),
                ('E_mail', models.EmailField(max_length=254)),
                ('Σελίδες_πακέτου', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Κόστος_πακέτου', models.CharField(max_length=20)),
                ('Σημειώσεις', models.CharField(max_length=500)),
                ('Ενεργός', models.BooleanField(default=True)),
            ],
        ),
    ]
