# Generated by Django 3.0.4 on 2020-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200305_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Σελίδες_πακέτου',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ταχ_Κώδικας',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
