# Generated by Django 3.0.4 on 2020-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200305_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='E_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Διεύθυνση',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Κόστος_πακέτου',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ονοματεπώνυμο',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Περιοχή',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Πόλη',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Σελίδες_πακέτου',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Σημειώσεις',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ταχ_Κώδικας',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
