# Generated by Django 3.0.4 on 2020-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200306_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='E_mail',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Διεύθυνση',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Κόστος_πακέτου',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ονοματεπώνυμο',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Περιοχή',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Πόλη',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Σελίδες_πακέτου',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Σημειώσεις',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ταχ_Κώδικας',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
