# Generated by Django 3.0.4 on 2020-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200306_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Διεύθυνση',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Περιοχή',
            field=models.CharField(blank=True, choices=[('Φ', 'Φλώρινα'), ('Α', 'Αμυνταιο'), ('Μ', 'Μελιτη')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Πόλη',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=100, null=True),
        ),
    ]
