# Generated by Django 3.0.4 on 2020-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20200306_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.PositiveIntegerField(blank=True, default=69, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Σελίδες_πακέτου',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ταχ_Κώδικας',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.PositiveIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
