# Generated by Django 3.0.4 on 2020-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200306_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Επωνυμία_Επιχείρησης',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.PositiveIntegerField(blank=True, default=69, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
