# Generated by Django 3.0.4 on 2020-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20200306_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Περιοχή',
            field=models.CharField(blank=True, choices=[('Φλώρινα', 'Φλώρινα'), ('Αμυνταιο', 'Αμυνταιο'), ('Μελίτη', 'Μελίτη')], default='Φλώρινα', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Πόλη',
            field=models.CharField(blank=True, choices=[('Φλώρινα', 'Φλώρινα'), ('Αμυνταιο', 'Αμυνταιο'), ('Μελίτη', 'Μελίτη')], default='Φλώρινα', max_length=100, null=True),
        ),
    ]
