# Generated by Django 3.0.4 on 2020-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20200309_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Σελίδες_πακέτου',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ταχ_Κώδικας',
            field=models.IntegerField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
