# Generated by Django 3.0.4 on 2020-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20200309_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Ταχ_Κώδικας',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
