# Generated by Django 3.0.4 on 2020-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20200309_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.IntegerField(blank=True, default=69, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
