# Generated by Django 3.0.4 on 2020-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_auto_20200310_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='E_mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Κινητό',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Τηλέφωνο',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Φαξ',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
