# Generated by Django 3.0.4 on 2020-03-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_auto_20200310_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer'},
        ),
    ]
