# Generated by Django 3.0.4 on 2020-03-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_auto_20200311_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
