# Generated by Django 3.0.4 on 2020-03-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_auto_20200311_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer'},
        ),
    ]
