# Generated by Django 3.0.4 on 2020-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_auto_20200311_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Ονοματεπώνυμο',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
