# Generated by Django 3.0.4 on 2020-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_auto_20200312_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Διεύθυνση',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
