# Generated by Django 3.0.4 on 2020-03-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0034_auto_20200315_1727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Πελάτες',
        ),
    ]
