# Generated by Django 3.0.4 on 2020-03-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0035_auto_20200316_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['Επωνυμία_Επιχείρησης'], 'verbose_name_plural': 'customer'},
        ),
    ]
