# Generated by Django 3.0.4 on 2020-03-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0036_auto_20200316_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Ενεργός',
            new_name='Κατάσταση',
        ),
    ]
