# Generated by Django 3.0.4 on 2020-03-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0039_auto_20200316_2210'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Πελατες',
        ),
    ]
