# Generated by Django 3.0.4 on 2020-03-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0040_auto_20200322_0105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Πελάτες',
        ),
    ]
