# Generated by Django 3.0.4 on 2020-03-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_auto_20200322_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['Επωνυμία_Επιχείρησης'], 'verbose_name_plural': 'Πελάτες'},
        ),
    ]
