# Generated by Django 3.0.4 on 2020-03-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0042_auto_20200328_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['Επωνυμία_Επιχείρησης'], 'verbose_name': 'Πελάτες', 'verbose_name_plural': 'Πελάτες'},
        ),
    ]
