# Generated by Django 3.0.4 on 2020-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0043_auto_20200330_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Περιοχή',
            field=models.CharField(blank=True, choices=[('Φλώρινα', 'Φλώρινα'), ('Αμύνταιο', 'Αμύνταιο'), ('Μελίτη', 'Μελίτη')], default='Φλώρινα', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Πόλη',
            field=models.CharField(blank=True, choices=[('Φλώρινα', 'Φλώρινα'), ('Αμύνταιο', 'Αμύνταιο'), ('Μελίτη', 'Μελίτη')], default='Φλώρινα', max_length=100, null=True),
        ),
    ]
