# Generated by Django 3.0.4 on 2020-04-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0050_auto_20200407_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Κατάσταση',
            field=models.BooleanField(default=True, help_text='Ενεργός πελάτης'),
        ),
    ]
