# Generated by Django 3.0.4 on 2020-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0051_auto_20200407_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Κατάσταση',
            field=models.BooleanField(default=True, help_text='<strong>Ενεργός πελάτης</strong>'),
        ),
    ]
